query getApplication($id: ID!) {
  app: application(id: $id) {
    ...ApplicationInfo
    loginRoute {
      ...RouteParts
    }
    layoutRoute {
      ...RouteParts
    }
    routes {
      ...RouteParts
    }
    menus {
      ...MenuParts
    }
  }
}

subscription subscibeUpdateRoute {
  updateRoute {
    id
    name
    component {
      id
      template
      blocks {
        key
        props
      }
    }
  }
}

fragment ApplicationInfo on Application {
  id
  name
  logo
  enabled
  description
  clientId
}

fragment MenuParts on Menu {
  id
  icon
  name
  path
  type
  index
  component {
    id
    template
    blocks {
      key
      props
    }
  }
  parent {
    id
    path
  }
}

fragment RouteParts on Route {
  id
  icon
  name
  path
  type
  index
  access
  enabled
  redirect
  authorized
  hideInBreadcrumb
  layout {
    pure
    hideMenu
  }
  parent {
    id
    path
  }
  component {
    id
    template
    blocks {
      key
      props
    }
  }
}
