query getApplication($id: ID!, $idType: ApplicationIdType = CLIENT_ID) {
  app: application(id: $id, idType: $idType) {
    ...ApplicationInfo
    loginRoute {
      ...RouteParts
    }
    layoutRoute {
      ...RouteParts
    }
    routes(where: { enabled: true }) {
      ...RouteParts
    }
    menus {
      ...MenuParts
    }
    dependencies {
      id
      name
      value
    }
    modules {
      id
      type
      name
      description
      values
    }
  }
}
subscription subscibeUpdateRoute {
  updateRoute {
    id
    name
    component {
      id
      template
      blocks {
        key
        props
      }
    }
  }
}

fragment ApplicationInfo on Application {
  id
  name
  logo
  enabled
  description
  clientId
}

fragment MenuParts on Menu {
  id
  icon
  name
  path
  type
  index
  hideInMenu
  hideInBreadcrumb
  hideChildrenInMenu
  component {
    id
    template
    blocks {
      key
      props
    }
  }
  parent {
    id
    path
  }
}

fragment RouteParts on Route {
  id
  icon
  name
  path
  type
  index
  access
  enabled
  redirect
  authorized
  hideInBreadcrumb
  layout {
    pure
    hideMenu
  }
  parent {
    id
    path
  }
  component {
    id
    template
    blocks {
      key
      props
    }
  }
  breadcrumb {
    id
    template
    blocks {
      key
      props
    }
  }
}
