query getApplication($id: ID!) {
  app: application(id: $id) {
    ...ApplicationInfo
    loginRoute {
      ...RouteParts
    }
    layoutRoute {
      ...RouteParts
    }
    routes {
      ...RouteParts
    }
    menus {
      id
      icon
      name
      path
      type
      index
      authorized
      hideInBreadcrumb
      enabled
      component {
        id
        template
      }
      parent {
        id
        path
      }
    }
  }
}

subscription subscibeUpdateRoute {
  updateRoute {
    id
    name
    component {
      id
      template
      props
    }
  }
}

fragment ApplicationInfo on Application {
  id
  name
  logo
  enabled
  description
  clientId
}

fragment RouteParts on Route {
  id
  icon
  name
  path
  type
  index
  access
  enabled
  redirect
  authorized
  hideInBreadcrumb
  layout {
    pure
    displayAsideSecondaryPanel
  }
  parent {
    id
    path
  }
  component {
    id
    template
  }
}
